sudo: required

language: node_js

node_js:
  - 'node'

cache: npm

before_install:
  - npm update

install:
  - npm ci
  - lerna bootstrap --hoist --npm-ci-mode

script:
  - lerna run build
  - npm run coveralls